languageCode = "en"
languageName = "English"
weight = 1
title = "opt-models"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo-darkmode.png"
  secondaryLogo = "img/logo.png"
  description = "A video compendium with accompanying code for people building and integrating large-scale optimization applications in the wild."
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Martin Laskowski"
  image = "img/martin.jpeg"
  headline = "Likes brown Cherry MX switches, green jellybeans ..."
#   bio = ""
  links = [
    { email = "mailto:caretaker@opt-models.org" },
#     { link = "https://link-to-some-website.com/" },
#     { codepen = "https://codepen.io/username" },
#     { discord = "https://discord.gg/invitecode" },
    { github = "https://github.com/MartinLaskowski" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
    { linkedin = "https://linkedin.com/in/martinlaskowski/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/martylasky" },
    { youtube = "https://www.youtube.com/@MartinLaskowski" },
#     { ko-fi = "https://ko-fi.com/username" },
  ]
