[[main]]
name = "compendium"
pageRef = "compendium"
weight = 1

[[main]]
name = "code"
pre = "github"
url = "https://github.com/orgs/opt-models/repositories"
identifier = "dTITSY7hX1"
weight = 2

# [[main]]
# name = "community"
# pageRef = "community"
# identifier = "MUB2RlvqGj"
# weight = 3

# [[main]]
# name = "wish lists"
# pageRef = "lists"
# identifier = "mMlPIzqekI"
# weight = 4

# [[main]]
# name = "resources"
# pageRef = "resources"
# identifier = "O3XtDfPKJz"
# weight = 5

[[main]]
name = "about"
pageRef = "about"
identifier = "O3XtDfPKJz"
weight = 6

[[footer]]
name = "privacy"
pageRef = "privacy"
identifier = "ekNullagKF"
weight = 1
