[[main]]
name = "The Compendium"
pageRef = "The Compendium"
weight = 1

[[main]]
name = "code"
pre = "github"
url = "https://github.com/orgs/opt-models/repositories"
identifier = "dTITSY7hX1"   
weight = 2

[[main]]
  name = "Welcome!"
  parent = "The Compendium"
  pageRef = "/"
  weight = 1
[[main]]
  name = "**RELEASING NOW:** Building the LEGO® Opt App"
  parent = "The Compendium"
  pageRef = "compendium/lego"
  weight = 2
[[main]]
  name = "[COMING SOON] Magical Opt Programming"
  parent = "The Compendium"
  pageRef = "compendium/magical-optimization-programming"
  weight = 3
[[main]]
  name = "[COMING SOON] Optimization Toolchain"
  parent = "The Compendium"
  pageRef = "compendium/toolchain"
  weight = 4
[[main]]
  name = "[COMING SOON] Five Parts of an Opt Model"
  parent = "The Compendium"
  pageRef = "compendium/optimization-model-parts"
  weight = 5
[[main]]
  name = "[COMING SOON] Dev Creature Comforts"
  parent = "The Compendium"
  pageRef = "compendium/dev-creature-comforts"
  weight = 6
[[main]]
  name = "[COMING SOON] Practical Optimization Theory"
  parent = "The Compendium"
  pageRef = "compendium/theory"
  weight = 7
[[main]]
  name = "[COMING SOON] Speeding Opt Apps"
  parent = "The Compendium"
  pageRef = "compendium/speeding-opt-apps"
  weight = 8
[[main]]
  name = "[COMING SOON] Optimization Market Predictions"
  parent = "The Compendium"
  pageRef = "compendium/optimization-markets-beyond-2024"
  weight = 9
[[main]]
  name = "[COMING SOON] Optimization ❤️ AI"
  parent = "The Compendium"
  pageRef = "compendium/opt-loves-ai"
  weight = 10
[[main]]
  name = "[COMING SOON] Thank you to ..."
  parent = "The Compendium"
  pageRef = "compendium/thank-you"
  weight = 11
[[main]]
  name = "[COMING SOON] Hey, Community!"
  parent = "The Compendium"
  pageRef = "compendium/hey-community"
  weight = 12

# [[main]]
# name = "community"
# pageRef = "community"
# identifier = "MUB2RlvqGj"
# weight = 3

# [[main]]
# name = "wish lists"
# pageRef = "lists"
# identifier = "mMlPIzqekI"
# weight = 4

# [[main]]
# name = "resources"
# pageRef = "resources"
# identifier = "O3XtDfPKJz"
# weight = 5

[[main]]
name = "about"
pageRef = "about"
identifier = "O3XtDfPKJz"
weight = 6

# [[footer]]
# name = "privacy"
# pageRef = "privacy"
# identifier = "ekNullagKF"
# weight = 1
