##### default parameters #####

# favicon
favicon = "images/favicon.png"

# logo
logo = "images/logo.png"
logo_darkmode = "images/logo-darkmode.png"
logo_width = "180px"
logo_height = "28px"          # logo_width does not work with .svg files
logo_webp = true              # if false, WEBP version of logo is not generated
logo_text = "opt-models"      # logo text only shows if logo is missing

# navbar
navbar_fixed = true           # if true, navbar is fixed to top of page

# dark/light theme functionality
theme_switcher = true         # if true, theme switcher toggle is shown in navbar
theme_default = "dark"        # one of: [light/dark/system]

# main sections
mainSections = ["blog"]

# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]

# google plugins
google_tag_manager = "" # example: G-XXXXXXXXXX see https://developers.google.com/tag-manager/
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx 

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""

# copyright
copyright = "© 2023 [Martin Laskowski](https://martinlaskowski.com/) | [Privacy](privacy-policy/) | [MIT License ](https://github.com/MartinLaskowski/opt-models.github.io/blob/main/LICENSE-FOR-CONTENT) unless otherwise noted | Theme by [Zeon Studio](https://zeon.studio)"

# image preloader module: https://github.com/gethugothemes/hugo-modules/tree/master/components/preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# top-right nav CTA button
[navigation_button]
enable = false
label = "Join the Discord"
link = "contact"

# search module: https://github.com/gethugothemes/hugo-modules/tree/master/search
[search]
enable = true
primary_color = "#121212"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true

# SEO meta data for OpenGraph / Twitter Card   SEO module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/basic-seo
[metadata]
keywords = ["Optimization", "Operations Research", "Data Science", "Optimization Models", "Optimization Software"]
description = "opt-models is a collection of optimization models and application-building code."
author = "martinlaskowski.com"
image = "images/og-image.png"


# site verifications module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/site-verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies module: https://github.com/gethugothemes/hugo-modules/tree/master/components/cookie-consent
[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories", "tags"]

# google map
[google_map]
enable = false
map_api_key = ""
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# subscription
[subscription]
enable = false

# mailchimp subsciption
mailchimp_form_action = "" # replace this url with yours
mailchimp_form_name = ""
